export interface DocSection {
  title: string;
  slug: string;
  description: string;
  badge?: string;
  category: string;
  content: {
    lead: string;
    sections: {
      id: string;
      title: string;
      description?: string;
      code?: {
        language: string;
        filename?: string;
        code: string;
      };
      points?: string[];
      callout?: {
        type: "tip" | "info" | "warning";
        title: string;
        text: string;
      };
    }[];
  };
}

export interface NavCategory {
  name: string;
  items: {
    title: string;
    slug: string;
    badge?: string;
  }[];
}

export const DOC_CATEGORIES: NavCategory[] = [
  {
    name: "Getting Started",
    items: [
      { title: "Introduction", slug: "introduction" },
      { title: "Installation & CLI", slug: "installation" },
      { title: "Hello World", slug: "hello-world" },
    ],
  },
  {
    name: "Language Basics",
    items: [
      { title: "Variables & Types", slug: "basics" },
      { title: "Control Flow", slug: "control-flow" },
      { title: "Functions & Returns", slug: "functions" },
    ],
  },
  {
    name: "Object-Oriented Programming",
    items: [
      { title: "Structs & Fields", slug: "structs" },
      { title: "Methods & Receivers", slug: "methods" },
      { title: "Interfaces & Polymorphism", slug: "interfaces" },
    ],
  },
  {
    name: "Concurrency & Runtime",
    items: [
      { title: "Goroutines (go)", slug: "concurrency" },
      { title: "Channels & Sync", slug: "channels" },
    ],
  },
  {
    name: "Standard Library",
    items: [
      { title: "Standard Library Overview", slug: "stdlib" },
      { title: "os & sys (System)", slug: "stdlib-os" },
      { title: "crypto (Hashing)", slug: "stdlib-crypto" },
      { title: "json (Serialization)", slug: "stdlib-json" },
      { title: "time (Benchmarking)", slug: "stdlib-time" },
      { title: "regex (Patterns)", slug: "stdlib-regex" },
    ],
  },
  {
    name: "Advanced Features",
    items: [
      { title: "Generics & Polymorphism", slug: "generics" },
      { title: "LLVM Compiler Architecture", slug: "architecture" },
    ],
  },
];

export const DOCS_DATA: Record<string, DocSection> = {
  introduction: {
    title: "Introduction to NP",
    slug: "introduction",
    category: "Getting Started",
    description: "Discover the design philosophy, core features, and architecture behind the NP programming language.",
    badge: "Core",
    content: {
      lead: "NP is a modern, statically-typed compiled language designed for developers who want the clean readability of Python coupled with the raw execution speed and concurrency model of C and Go.",
      sections: [
        {
          id: "why-np",
          title: "Why NP?",
          description: "Many languages force developers to choose between ergonomic developer experience and runtime performance. NP bridges this divide by compiling directly to native machine code via LLVM while maintaining elegant, readable syntax.",
          points: [
            "Native Speed: Compiles ahead-of-time (AOT) via LLVM IR into optimized standalone machine binaries.",
            "Go-Style Concurrency: Built-in 'go' keyword for lightweight goroutines and CSP channels.",
            "Zero Overhead OOP: Value and pointer receiver methods with direct memory layouts and vtable interface dispatch.",
            "Rich Standard Library: Production-ready modules for os, crypto, json, time, regex, and sys.",
            "Modern Toolchain: One unified CLI for building, running, and testing.",
          ],
        },
        {
          id: "language-at-a-glance",
          title: "Language at a Glance",
          description: "Here is a quick demonstration showing structs, methods, goroutines, and channels working seamlessly together in NP.",
          code: {
            language: "np",
            filename: "main.np",
            code: `import "time"

struct Task {
    id: int
    name: string
}

fn (t Task) execute(out: chan string) {
    time.sleep(10)
    out <- "Task " + t.name + " completed!"
}

fn main() {
    let ch = make(chan string, 2)
    let t1 = Task{id: 1, name: "Data Processing"}
    let t2 = Task{id: 2, name: "Index Optimization"}

    go t1.execute(ch)
    go t2.execute(ch)

    print(<-ch)
    print(<-ch)
}`,
          },
          callout: {
            type: "tip",
            title: "Zero Dependencies",
            text: "Binaries generated by the NP compiler are self-contained native executables with no Python runtime or heavy VM required.",
          },
        },
      ],
    },
  },

  installation: {
    title: "Installation & CLI Toolchain",
    slug: "installation",
    category: "Getting Started",
    description: "How to set up the NP compiler, configure environment variables, and use the unified CLI tool.",
    content: {
      lead: "The NP toolchain consists of the compiler driver 'np', the LLVM code generator, and the NP runtime library.",
      sections: [
        {
          id: "prerequisites",
          title: "System Prerequisites",
          description: "NP compiles to native code via LLVM and clang. Ensure your machine has:",
          points: [
            "LLVM & Clang (version 15 or higher)",
            "GCC or MSVC toolchain for system linking",
            "C++20 compliant host compiler for building the compiler itself (CMake 3.20+)",
          ],
        },
        {
          id: "cli-commands",
          title: "The NP CLI Tool",
          description: "NP provides an intuitive command-line interface inspired by Go and Cargo.",
          code: {
            language: "bash",
            filename: "Terminal",
            code: `# Build an executable binary
np build main.np -o myapp

# Build and run immediately
np run main.np

# Build with optimization levels (O1, O2, O3)
np build main.np -O3 -o myapp-release

# Emit LLVM IR for inspection
np build main.np --emit-llvm -o myapp.ll

# Run test suite
np test ./tests/...`,
          },
          callout: {
            type: "info",
            title: "Cross Compilation",
            text: "Because NP utilizes LLVM, you can target x86_64, aarch64 (ARM64), and WebAssembly by passing the --target flag.",
          },
        },
      ],
    },
  },

  "hello-world": {
    title: "Hello World & Pipeline",
    slug: "hello-world",
    category: "Getting Started",
    description: "Writing your first NP program and understanding how the compilation pipeline transforms code into native binary.",
    content: {
      lead: "Every journey begins with a clean program. Let's write, compile, and run your first NP program.",
      sections: [
        {
          id: "first-code",
          title: "Writing Hello World",
          description: "Create a new file named `hello.np` with the following content:",
          code: {
            language: "np",
            filename: "hello.np",
            code: `fn main() {
    let message: string = "Hello, NP World!"
    print(message)
}`,
          },
        },
        {
          id: "run-it",
          title: "Compiling and Executing",
          description: "Run the program with one command:",
          code: {
            language: "bash",
            filename: "Terminal",
            code: `$ np run hello.np
Hello, NP World!`,
          },
        },
        {
          id: "compilation-stages",
          title: "What Happens Under The Hood?",
          description: "The NP compiler executes four distinct stages:",
          points: [
            "1. Lexing & AST Parsing: Tokenizes input and builds an abstract syntax tree with full source location tracking.",
            "2. Type Checking & Symbol Resolution: Validates static types, method signatures, and scope boundaries.",
            "3. LLVM IR Generation: Translates high-level NP semantics into optimized intermediate representation.",
            "4. Native Code Generation: Clang/LLVM links runtime primitives into an ELF, Mach-O, or PE binary.",
          ],
        },
      ],
    },
  },

  basics: {
    title: "Variables & Primitive Types",
    slug: "basics",
    category: "Language Basics",
    description: "Type system, immutable and mutable bindings, and primitive data types in NP.",
    content: {
      lead: "NP is statically typed with powerful type inference, allowing you to write terse code while enjoying strict compile-time safety.",
      sections: [
        {
          id: "primitive-types",
          title: "Builtin Primitive Types",
          description: "NP provides standard fixed-width numeric and string primitives:",
          points: [
            "int: Signed 64-bit integer",
            "float: 64-bit IEEE 754 floating point number",
            "bool: Boolean value (true or false)",
            "string: UTF-8 encoded string slice",
            "void: Unit return type for functions",
          ],
        },
        {
          id: "variable-declaration",
          title: "Variable Declarations",
          description: "Use 'let' for mutable variables and 'const' for compile-time constants.",
          code: {
            language: "np",
            filename: "variables.np",
            code: `fn main() {
    // Explicit type declaration
    let count: int = 42
    let ratio: float = 3.14159
    let is_ready: bool = true

    // Type inference (compiler infers 'string')
    let greeting = "Welcome to NP"

    // Mutable reassignment
    count = count + 1

    // Constant declaration
    const MAX_BUFFER: int = 1024
    
    print(greeting)
    print(count)
}`,
          },
        },
      ],
    },
  },

  "control-flow": {
    title: "Control Flow & Loops",
    slug: "control-flow",
    category: "Language Basics",
    description: "Branching with if/else, iterative loops with while and for-in, and loop control statements.",
    content: {
      lead: "NP provides straightforward control flow structures without unnecessary syntax clutter.",
      sections: [
        {
          id: "conditional-branching",
          title: "If / Else Statements",
          description: "Conditions do not require surrounding parentheses:",
          code: {
            language: "np",
            filename: "conditions.np",
            code: `let score = 85

if score >= 90 {
    print("Grade: A")
} else if score >= 80 {
    print("Grade: B")
} else {
    print("Grade: C")
}`,
          },
        },
        {
          id: "loops",
          title: "While and For-In Loops",
          description: "Use while for condition-based repetition, or for-in to iterate ranges and collections:",
          code: {
            language: "np",
            filename: "loops.np",
            code: `// While loop
let i = 0
while i < 5 {
    if i == 2 {
        i = i + 1
        continue
    }
    print(i)
    i = i + 1
}

// For-in range loop
for item in 0..10 {
    if item > 7 {
        break
    }
    print(item)
}`,
          },
        },
      ],
    },
  },

  functions: {
    title: "Functions & Returns",
    slug: "functions",
    category: "Language Basics",
    description: "First-class functions, multiple return values, named returns, and lambda closures.",
    content: {
      lead: "Functions in NP are first-class citizens: they can take multiple arguments, return multiple values, and be stored in variables or passed as closures.",
      sections: [
        {
          id: "multiple-returns",
          title: "Multiple Return Values",
          description: "Returning tuples or results with error status is a first-class feature in NP:",
          code: {
            language: "np",
            filename: "multi_return.np",
            code: `fn divide(numerator: int, denominator: int) -> (int, bool) {
    if denominator == 0 {
        return (0, false)
    }
    return (numerator / denominator, true)
}

fn main() {
    let (result, ok) = divide(10, 2)
    if ok {
        print("Success:")
        print(result)
    } else {
        print("Division by zero error")
    }
}`,
          },
        },
        {
          id: "first-class-lambdas",
          title: "First-Class Functions & Closures",
          description: "Pass functions as parameters to create higher-order pipelines:",
          code: {
            language: "np",
            filename: "closure.np",
            code: `fn make_adder(x: int) -> fn(int) -> int {
    return fn(y: int) -> int {
        return x + y
    }
}

fn main() {
    let addTen = make_adder(10)
    print(addTen(5))  // Outputs: 15
}`,
          },
        },
      ],
    },
  },

  structs: {
    title: "Structs & Data Modeling",
    slug: "structs",
    category: "Object-Oriented Programming",
    description: "Defining custom data types, instantiating structs, and memory layout in NP.",
    content: {
      lead: "Structs are the primary vehicle for custom data representation in NP. They are packed efficiently in memory with deterministic C-compatible layout.",
      sections: [
        {
          id: "defining-structs",
          title: "Struct Definition & Initialization",
          description: "Declare structured types with named fields and instantiate them with field initializers:",
          code: {
            language: "np",
            filename: "structs.np",
            code: `struct Point {
    x: float
    y: float
}

struct User {
    id: int
    username: string
    active: bool
    location: Point
}

fn main() {
    let p = Point{x: 10.5, y: 20.0}
    let u = User{
        id: 1001,
        username: "alex",
        active: true,
        location: p,
    }

    print(u.username)
    print(u.location.x)
}`,
          },
          callout: {
            type: "info",
            title: "Memory Layout",
            text: "NP structs do not have hidden object headers or virtual table pointers unless cast to an interface, ensuring maximum cache locality.",
          },
        },
      ],
    },
  },

  methods: {
    title: "Methods & Receivers",
    slug: "methods",
    category: "Object-Oriented Programming",
    description: "Associating functions with types via value receivers and mutating pointer receivers.",
    content: {
      lead: "NP follows the elegant receiver pattern: methods are declared with an explicit receiver preceding the function name.",
      sections: [
        {
          id: "receiver-syntax",
          title: "Value and Pointer Receivers",
          description: "Use value receivers for read-only access and mutating receivers when altering fields:",
          code: {
            language: "np",
            filename: "methods.np",
            code: `struct Counter {
    value: int
}

// Read-only value receiver
fn (c Counter) get_val() -> int {
    return c.value
}

// Mutating receiver (modifies the underlying instance)
fn (mut c Counter) increment(amount: int) {
    c.value = c.value + amount
}

fn main() {
    let mut ctr = Counter{value: 0}
    ctr.increment(5)
    ctr.increment(10)
    print(ctr.get_val()) // Outputs: 15
}`,
          },
        },
      ],
    },
  },

  interfaces: {
    title: "Interfaces & Polymorphism",
    slug: "interfaces",
    category: "Object-Oriented Programming",
    description: "Structural typing and dynamic dispatch using NP interface contracts.",
    content: {
      lead: "NP interfaces specify behavior through method sets. Types implement interfaces implicitly—no 'implements' keyword needed.",
      sections: [
        {
          id: "interface-definition",
          title: "Defining & Implementing Interfaces",
          description: "Any type that implements all required methods satisfies the interface automatically:",
          code: {
            language: "np",
            filename: "interfaces.np",
            code: `interface Shape {
    fn area() -> float
    fn name() -> string
}

struct Circle {
    radius: float
}

fn (c Circle) area() -> float {
    return 3.14159 * c.radius * c.radius
}

fn (c Circle) name() -> string {
    return "Circle"
}

fn print_info(s: Shape) {
    print(s.name())
    print(s.area())
}

fn main() {
    let c = Circle{radius: 5.0}
    print_info(c) // Implicit dynamic polymorphism
}`,
          },
          callout: {
            type: "tip",
            title: "Fat Pointer VTables",
            text: "Interface instances in NP are fat pointers containing a data pointer and an LLVM vtable pointer for near-zero dispatch overhead.",
          },
        },
      ],
    },
  },

  concurrency: {
    title: "Goroutines & Concurrency",
    slug: "concurrency",
    category: "Concurrency & Runtime",
    description: "Lightweight concurrent routines spawned with the 'go' keyword.",
    content: {
      lead: "NP brings Go's revolutionary concurrency model to the LLVM native ecosystem. Launch thousands of concurrent tasks with minimal stack footprints.",
      sections: [
        {
          id: "go-keyword",
          title: "Spawning Goroutines",
          description: "Prefix any function call with 'go' to schedule it concurrently on the runtime thread pool:",
          code: {
            language: "np",
            filename: "concurrency.np",
            code: `import "time"

fn worker(id: int) {
    print("Worker running: ")
    print(id)
    time.sleep(50)
    print("Worker finished")
}

fn main() {
    // Spawns 3 lightweight concurrent routines
    go worker(1)
    go worker(2)
    go worker(3)

    time.sleep(100)
    print("All tasks scheduled.")
}`,
          },
        },
      ],
    },
  },

  channels: {
    title: "Channels & Synchronization",
    slug: "channels",
    category: "Concurrency & Runtime",
    description: "Communicating Sequential Processes (CSP) via typed FIFO channels.",
    content: {
      lead: "Do not communicate by sharing memory; instead, share memory by communicating. NP channels provide safe, lock-free communication between goroutines.",
      sections: [
        {
          id: "channel-operations",
          title: "Making & Using Channels",
          description: "Channels can be unbuffered or buffered, and use the arrow operator '<-' for sending and receiving:",
          code: {
            language: "np",
            filename: "channels.np",
            code: `fn compute(out: chan int) {
    let sum = 0
    let i = 1
    while i <= 100 {
        sum = sum + i
        i = i + 1
    }
    out <- sum // Send value into channel
}

fn main() {
    // Create a buffered channel with capacity 1
    let result_ch = make(chan int, 1)

    go compute(result_ch)

    let total = <-result_ch // Blocking receive
    print("Computed total:")
    print(total)
}`,
          },
        },
      ],
    },
  },

  stdlib: {
    title: "Standard Library Overview",
    slug: "stdlib",
    category: "Standard Library",
    description: "Comprehensive guide to NP's batteries-included standard library packages.",
    content: {
      lead: "NP ships with a robust standard library providing essential system, cryptographic, serialization, and string utilities out of the box.",
      sections: [
        {
          id: "included-packages",
          title: "Standard Packages at a Glance",
          points: [
            "os: File I/O, directory traversal, system paths, environment variables",
            "crypto: SHA256, MD5, cryptographic hashing and digests",
            "json: High performance JSON encoding, decoding, and value traversal",
            "time: Monotonic clocks, wall clocks, timers, and precision benchmarking",
            "regex: High performance regular expression pattern matching and capture",
            "sys: Hardware inspection, CPU core counts, platform identification",
          ],
        },
        {
          id: "importing",
          title: "Importing Modules",
          code: {
            language: "np",
            filename: "modules.np",
            code: `import "os"
import "crypto"
import "json"
import "time"

fn main() {
    let now = time.now_ms()
    let hash = crypto.sha256("antigravity")
    print(hash)
}`,
          },
        },
      ],
    },
  },

  "stdlib-os": {
    title: "os & sys Packages",
    slug: "stdlib-os",
    category: "Standard Library",
    description: "File manipulation, process management, environment variables, and hardware detection.",
    content: {
      lead: "The os and sys modules allow NP programs to interact natively with POSIX and Windows operating system interfaces.",
      sections: [
        {
          id: "file-io",
          title: "File Operations with os",
          code: {
            language: "np",
            filename: "file_io.np",
            code: `import "os"

fn main() {
    // Write text to file
    let path = "output.txt"
    os.write_file(path, "Build with NP Native LLVM\\n")

    // Check file existence
    if os.exists(path) {
        let content = os.read_file(path)
        print("Read content:")
        print(content)
    }

    // Read environment variable
    let user = os.getenv("USER")
    print(user)
}`,
          },
        },
        {
          id: "sys-package",
          title: "System Hardware & Platform",
          code: {
            language: "np",
            filename: "system.np",
            code: `import "sys"

fn main() {
    let cores = sys.num_cpus()
    let arch = sys.arch()
    let os_name = sys.os_name()

    print("Platform: " + os_name + "/" + arch)
    print("CPU Cores: ")
    print(cores)
}`,
          },
        },
      ],
    },
  },

  "stdlib-crypto": {
    title: "crypto Package",
    slug: "stdlib-crypto",
    category: "Standard Library",
    description: "Cryptographic hashing algorithms including SHA256 and MD5 for data integrity and authentication.",
    content: {
      lead: "The crypto package provides secure, hardware-accelerated implementations of industry-standard hash functions.",
      sections: [
        {
          id: "sha256-md5",
          title: "Computing Digests",
          code: {
            language: "np",
            filename: "hashing.np",
            code: `import "crypto"

fn main() {
    let data = "secure-payload-token"

    let sha_digest = crypto.sha256(data)
    let md5_digest = crypto.md5(data)

    print("SHA256: " + sha_digest)
    print("MD5:    " + md5_digest)
}`,
          },
        },
      ],
    },
  },

  "stdlib-json": {
    title: "json Package",
    slug: "stdlib-json",
    category: "Standard Library",
    description: "High speed JSON serialization and parsing without external dependencies.",
    content: {
      lead: "Serialize and parse JSON records directly within NP programs for API integrations and configuration files.",
      sections: [
        {
          id: "json-encode-decode",
          title: "JSON Encoding & Parsing",
          code: {
            language: "np",
            filename: "json_test.np",
            code: `import "json"

fn main() {
    let payload = "{\\"service\\":\\"auth\\",\\"port\\":8080,\\"active\\":true}"
    
    let parsed = json.parse(payload)
    let port = json.get_int(parsed, "port")
    let service = json.get_string(parsed, "service")

    print("Service: " + service)
    print("Port: ")
    print(port)
}`,
          },
        },
      ],
    },
  },

  "stdlib-time": {
    title: "time Package",
    slug: "stdlib-time",
    category: "Standard Library",
    description: "High resolution timers, sleep durations, and microsecond performance benchmarking.",
    content: {
      lead: "Measure runtime latency with high-precision monotonic clocks and manage sleep intervals.",
      sections: [
        {
          id: "benchmarking",
          title: "Measuring Latency & Sleeping",
          code: {
            language: "np",
            filename: "benchmark.np",
            code: `import "time"

fn main() {
    let start = time.now_ms()

    // Simulate work
    time.sleep(25)

    let elapsed = time.now_ms() - start
    print("Operation elapsed time (ms):")
    print(elapsed)
}`,
          },
        },
      ],
    },
  },

  "stdlib-regex": {
    title: "regex Package",
    slug: "stdlib-regex",
    category: "Standard Library",
    description: "Regular expression matching, submatch extraction, and string replacements.",
    content: {
      lead: "Fast pattern matching powered by the NP regex engine.",
      sections: [
        {
          id: "regex-matching",
          title: "Pattern Testing & Match Extraction",
          code: {
            language: "np",
            filename: "regex.np",
            code: `import "regex"

fn main() {
    let email = "dev@example.com"
    let pattern = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"

    if regex.matches(pattern, email) {
        print("Valid email address!")
    } else {
        print("Invalid email format.")
    }
}`,
          },
        },
      ],
    },
  },

  generics: {
    title: "Generics & Type Parameters",
    slug: "generics",
    category: "Advanced Features",
    description: "Writing reusable, type-safe functions and data structures without runtime penalty.",
    content: {
      lead: "NP generics enable polymorphic functions and container structures that are monomorphized at compile time for zero abstraction cost.",
      sections: [
        {
          id: "generic-functions",
          title: "Generic Function Signatures",
          description: "Declare type parameters in square brackets:",
          code: {
            language: "np",
            filename: "generics.np",
            code: `fn identity[T](val: T) -> T {
    return val
}

fn pair_first[A, B](first: A, second: B) -> A {
    return first
}

fn main() {
    let x = identity[int](42)
    let s = identity[string]("polymorphic")
    let p = pair_first[string, int]("NP", 2026)

    print(x)
    print(s)
    print(p)
}`,
          },
          callout: {
            type: "tip",
            title: "Monomorphization",
            text: "Like C++ templates and Rust generics, NP instantiates specialized LLVM code for each concrete type, producing optimal native assembly.",
          },
        },
      ],
    },
  },

  architecture: {
    title: "LLVM Compiler Architecture",
    slug: "architecture",
    category: "Advanced Features",
    description: "Deep dive into the lexer, parser, semantic analyzer, and LLVM intermediate representation pipeline.",
    content: {
      lead: "Explore how NP compiles human-readable code into blazing fast native machine instructions.",
      sections: [
        {
          id: "pipeline-breakdown",
          title: "The Four Core Stages",
          points: [
            "Front-End: Tokenizer and recursive descent parser construct typed Abstract Syntax Trees (AST).",
            "Semantic Pass: Type inference, type checking, method table binding, and closure capture analysis.",
            "Middle-End: LLVM IR Builder converts AST nodes into Static Single Assignment (SSA) form.",
            "Back-End & Linking: LLVM optimization passes (-O1, -O2, -O3), target machine code generation, and linkage with libnp_runtime.",
          ],
        },
        {
          id: "llvm-ir-sample",
          title: "Sample Generated LLVM IR",
          description: "When compiling a simple addition function, NP generates clean LLVM IR:",
          code: {
            language: "llvm",
            filename: "add.ll",
            code: `; ModuleID = 'add.np'
source_filename = "add.np"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define i64 @add(i64 %a, i64 %b) {
entry:
  %res = add nsw i64 %a, %b
  ret i64 %res
}`,
          },
        },
      ],
    },
  },
};
